### ISSUE TITLE
add inbound integration 

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-classic#15]
This will be a simple form-post integration (similar to `leadconduit-default.inbound`), except it will give a LeadConduit Classic-formatted response. 

Sample good response: 

```xml
<!DOCTYPE response SYSTEM "https://app.leadconduit.com/dtd/response-v2-basic.dtd">
<response>
    <result>success</result>
    <leadId>05cw6wgai</leadId>
    <url><![CDATA[https://app.leadconduit.com/leads?id=05cw6wgai]]></url>
</response>
```

Sample failure response: 

```xml
<!DOCTYPE response SYSTEM "https://app.leadconduit.com/dtd/response-v2-basic.dtd">
<response>
    <result>failure</result>
    <reason>duplicate</reason>
    <leadId>05cw6wa68</leadId>
    <url><![CDATA[https://app.leadconduit.com/leads?id=05cw6wa68]]></url>
</response>
```

The DTD URL will stay the same, but the `leadId` and `url` values will reflect the LC lead (i.e., BSON lead IDs and a URL like `https://next.leadconduit.com/events/5a6f47fa52a82e54fbc833e1`). 

See also [this KB article](https://support.activeprospect.com/hc/en-us/articles/201325969-Understanding-the-LeadConduit-Classic-Server-Response) for more details on the Classic response.

**Comment by chasingSublimity** [comment]
added in #17
