### ISSUE TITLE
alphabetize & stringify reason values

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-classic#7]
When there are multiple `<reason/>` values returned by LC Classic, they aren't necessarily in any order. Currently this integration takes them in whatever order they come, leading to falsely differentiated values. 

For example, one lead's `reason` might get set to "invalid phone_1, invalid email" but another might get set to "invalid email, invalid phone_1". This results in reporting views such as this: 

![screen shot 2016-02-09 at 2 23 10 pm](https://cloud.githubusercontent.com/assets/5596/12929515/b067bf0c-cf38-11e5-9801-0ac17ab5ac48.png)

**Comment by cgrayson** [comment]
Though thinking about it now, I also wonder if it's problematic for `reason` to be an array. What do you think, @alexkwolfe?

**Comment by alexkwolfe** [comment]
Yes. I do think that's problematic. The reason is meant to be a string. IMO, this integration should sort and join the reasons.
